<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => 'Accueil',
    'Profile' => 'Profil',
    'Community' => 'Communauté',
    'Depression' => 'Dépression',
    'Anxiety' => 'Anxiété',
    'More Help' => 'Aide supplémentaire',
    'Helping Fellow Members' => 'Donner et recevoir du soutien',
    'Members' => 'Membres',
    'Community Settings' => 'Milieu communautaire',
    'Logout / (' => 'Fermeture la session / (',
    'Logout / ' => 'Fermeture la session / ',
    'Logout' => 'Fermeture la session',
    'Signup' => 'Inscription',
    'Forum' => 'Forums',
    'Threads' => 'Discussions',
    'Posts' => 'Contributions',
    'Create new thread' => 'Lancer une nouvelle discussion',

    'Members List'=> 'Liste des membres',
    'Moderation Team' => 'Équipe d’animation',
    'Member View' => 'Survol des membres',
    'Member' => 'Membre',
    'Member since {date}' => 'Date d’adhésion {date}',
    'Find all threads started by {name}' => 'Trouver toutes les discussions ouvertes par {name} ',
    'Find all posts created by {name}' => 'Trouver tous les messages rédigés par {name}',

    'Username' => 'Membre',
    'View Member' => 'Survol des membres',



];
