<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => 'Accueil',
    'Profile' => 'Profil',
    'Community' => 'Communauté',
    'Depression' => 'Dépression',
    'Anxiety' => 'Anxiété',
    'More Help' => 'Aide supplémentaire',
    'Helping Fellow Members' => 'Donner et recevoir du soutien',
    'Members' => 'Membres',
    'Community Settings' => 'Milieu communautaire',
    'Logout / (' => 'Fermeture la session / (',
    'Logout / ' => 'Fermeture la session / ',
    'Logout' => 'Fermeture la session',
    'Signup' => 'Inscription',
    'Forum' => 'Forums',
    'Threads' => 'Discussions',
    'Posts' => 'Contributions',
    'Create new thread' => 'Lancer une nouvelle discussion',

    'Members List'=> 'Liste des membres',
    'Moderation Team' => 'Équipe d’animation',
    'Member View' => 'Survol des membres',
    'Member' => 'Membre',
    'Member since {date}' => 'Date d’adhésion {date}',
    'Find all threads started by {name}' => 'Trouver toutes les discussions ouvertes par {name} ',
    'Find all posts created by {name}' => 'Trouver tous les messages rédigés par {name}',

    'Username' => 'Membre',
    'View Member' => 'Survol des membres',
    'Latest Post' => 'Activités récentes',
    '{n, plural, =1{# active user} other{# active users}} (in the past 15 minutes)' => '{n, plural, =1{# membres en ligne} other{# membres en ligne}} (des 15 derniéres minutes)',
    '{n, plural, =1{# guest} other{# guests}}' => '{n, plural, =1{# guest} other{# guests}}',
    '{n, plural, =1{# member} other{# members}}' => '{n, plural, =1{# membres} other{# membres}}',
    'Unread posts' => 'messages sans réponse',
    'Thread' => 'Discussion',
    'Replies' => 'Réponses',
    'Views' => 'Vulues',
    'Browsing this forum' => 'En ligne',
    '{n, plural, =1{# anonymous user} other{# anonymous users}}' => '{n, plural, =1{# Utilisateurs invisibles} other{# Utilisateurs invisibles}}',
    'Results per page' => 'Résultats par page',
    'Role' => 'rôle',
    'Joined' => 'Date d\'adhésion',
    'Actions' => 'actes',
    'Advanced Search Form' => 'Recherche avancée',
    'Search Forum' => 'Rechercher',
    'Find words' => 'Rechercher par mots-clés',
    'Match' => 'Rechercher',
    'all words' => 'tous les termes',
    'any word' => 'n\'importe quels de ces termes',
    'Author' => 'auter:',
    'Date from' => 'dans le temps de:',
    'Date to' => 'dans le temps à:',
    'Search in Forums' => 'Rechercher dans le(s) forum(s):',
    'Search in' => 'Rechercher dans:',
    'Post contents' => 'Le contenu des messages',
    'threads titles' => 'Les titres des discussions',
    'Display as' => 'Afficher les résultats sous forme de:',
    'as posts' => 'Messages',
    'as threads' => 'Discussions',
    'Search' => 'rechercher',
    'My Profile' => 'Mon profil',
    'Forum Details' => 'Détails du forum',
    'Message' =>    'Messages' ,
    'Subscriptions' => 'Inscriptions',
    'Time Zone' => 'fuseau horaire',
    'Select your time zone for proper dates display...' => 'Vorte fuseau horaire',
    'What is my time zone?' => 'Quel est mon fuseau horaire',
    'Signature under each post' => 'Signature',
    'Save changes' => 'Sauvegarder les modification',
    'Messages Inbox' => 'Boite de réception ',
    'Send Message' => 'Envoyé',
    'New Message' => 'Nouveau message',
    'From' => 'De',
    'Topic' => 'Sujet',
    'Sent' => 'Envoyé',
    'Sent Messages' => 'Envoyé',
    'Send to' => 'À',
    'Select a member...' => 'sélectionner des destinataires',
    'Message Topic' => 'Sujet',
    'Message Content' => 'Corps du message',
    //'Send Message' => 'Envoyé le message',
    'Thread\'s Name' => 'Titre de discussion',
    'New Posts' => 'Noueveaux contributions',
    'Unsubscribe Selected Threads' => 'Desinscire',






];
